MODULE PaymentProcessDashboardNew;

REQUIRE PaymentProcessDashboard, Agreement, Contract, Payment;

differenceSumPaid 'Разница (ст.-опл.)' (Agreement a) = sum(a) (-) paidPayment(a); 

EXTEND FORM dialogAgreements
    PROPERTIES(o) READONLY paidPayment AFTER sum(o)
    PROPERTIES(o) READONLY differenceSumPaid AFTER paidPayment(o)
;

DESIGN dialogAgreements {
    PROPERTY (paidPayment(o)) {caption = 'Оплачено по факт'; charWidth = 10;}
    PROPERTY (differenceSumPaid(o)) {charWidth = 10;}
}

