MODULE AgreementNew;

REQUIRE Agreement, DebtAgreement, Contract;

onDelAgreement 'Удалить с задол.' (Agreement a) {
    ASK 'Вы действительно хотите удалить Соглашение\nи связанные с ним Задолженности?' DO {
       IF (nameType(a) = 'ДСГ' OR nameType(a) = 'ПРТ') THEN DELETE Debt d WHERE agreement(d) = a; // AND NOT paid(d);
       DELETE a;   
    }
}

EXTEND FORM contract
    PROPERTIES(ag) onDelAgreement SHOWIF (nameType(ag) = 'ДСГ' OR nameType(ag) = 'ПРТ') TOOLBAR 
;
