MODULE RestApiXmlTracker;

GROUP default_status;

id = DATA LOCAL STRING(INTEGER);
name = DATA LOCAL STRING(INTEGER);
id1 = DATA LOCAL STRING(INTEGER);
name1 = DATA LOCAL STRING(INTEGER);
description = DATA LOCAL STRING(INTEGER);
type = DATA LOCAL STRING();

FORM RestApiTrackers
PROPERTIES() type ATTR

OBJECTS tracker = INTEGER

PROPERTIES(tracker) id, name, description
PROPERTIES(tracker) IN default_status id1 EXTID 'id' ATTR, name1 EXTID 'name' ATTR;